FROM python:3.6 AS builder

RUN python -m pip install protobuf==3.12.2 grpcio==1.38.1 

WORKDIR route_guide

COPY route_guide/ .
COPY server.crt .
COPY server.key .

EXPOSE 50051

ENTRYPOINT ["python", "route_guide_server.py"]